apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: d9
  name: d9
spec:
  replicas: 2
  selector:
    matchLabels:
      app: d9
  template:
    metadata:
      labels:
        app: d9
    spec:
      containers:
      - image: drupal:9.2.0-php8.0-apache
        name: drupal
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: d9-service
spec:
  selector:
    app: d9
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30011                       
